---
- name: "Download the oauth2-proxy tarball for version {{ oauth2_proxy_version }}"
  get_url:
    url: "https://github.com/bitly/oauth2_proxy/releases/download/v{{ oauth2_proxy_version }}/oauth2_proxy-{{ oauth2_proxy_version }}.linux-amd64.go1.6.tar.gz"
    dest: "/tmp/oauth2_proxy-{{ oauth2_proxy_version }}.linux-amd64.go1.6.tar.gz"
    mode: '0644'
  notify: 'restart-ansible-role-oauth2proxy'

- name: 'Create the user that the oauth2_proxy daemon will run as'
  user:
    name: "{{ oauth2_proxy_daemon_user }}"

- include: "{{ ansible_distribution }}.yml"

- meta: flush_handlers

- name: 'Ensure that the oauth2proxy daemon is running'
  service:
    name: 'oauth2proxy'
    state: 'started'
    enabled: 'yes'
